### ISSUE TITLE
Fatal error on creation of a new page

### ISSUE THREAD

**Issue by hvorragend** [phaidon/Wikula#68]
http://domainde/index.php?module=wikula&type=user&func=main&tag=Testlink1

Fatal error: Call to a member function format() on a non-object in /www/htdocs/host/modules/Wikula/lib/Wikula/Controller/User.php on line 146

**Comment by hvorragend** [comment]
And after saving a page:

```
WARN (4): E_WARNING: Invalid argument supplied for foreach() in User.php Zeile 799
WARN (4): E_WARNING: Invalid argument supplied for foreach() in User.php Zeile 811 
```

**Comment by phaidon** [comment]
@hvorragend Thanks for the report. At the moment I can not reproduce it.

Are you using the current of Wikula?
Which version of Zikula are you using?

**Comment by hvorragend** [comment]
Yes, it it the latest Git version and I am using Zikula 1.3.2dev.

line 145: `$datetime = $page['time']->format('Y-m-d H:i:s');`

**Comment by hvorragend** [comment]
Give me a second. I am updating my files.

**Comment by hvorragend** [comment]
Core and module updated now. But sorry, I am still having the same error.

**Comment by phaidon** [comment]
Do you have enabled the subscriptions in the admin config menu?

**Comment by hvorragend** [comment]
No

**Comment by phaidon** [comment]
Can you fully remove and install the Wikula module? Thanks

**Comment by hvorragend** [comment]
Yes, done now and nothing changes.
That's a strain with all the other errors.

**Comment by hvorragend** [comment]
Again: 
- ALL database tables deleted
- News Zikula installation
- Wikula and others installed
- First link added to the 'homepage' page
- Open the 'homepage' page
- Click on the link 
- Error

**Comment by phaidon** [comment]
Is there also an error on the 'show' (first) page?

What is the error message?

**Comment by hvorragend** [comment]
See ticket content above.

**Comment by phaidon** [comment]
The Zeile 799 and 811 warnings appeared when the Wakka Hook was not activated. But meanwhile I fixed this warnings. So this warnings can't appear anymore. The foreach loop is now protected by an if statement. If the array is empty the loop will not entered anymore:

https://github.com/phaidon/Wikula/commit/947a40d344152bf40daee673811056840c60ef03

**Comment by phaidon** [comment]
> Fatal error: Call to a member function format() on a non-object in /www/htdocs/host/modules/Wikula/lib/Wikula/Controller/User.php on line 146

This appears if all revistions have the value latest = N. 
Maybe this problem is solved with the last commit.
To test it you have to reinstall the module or set the value 'latest' of the last revision of the hompage tag in the database to N.

**Comment by hvorragend** [comment]
Sorry, it is not fixed yet.

Now I have three revisions:

```
1   HomePage    2012-01-12 18:00:05     Welcome to your Wiki!   demoadmin   demoadmin   N   Initial Insert  page
2   HomePage    2012-01-12 18:02:59     Welcome to your Wiki! [[Test]]  demoadmin   demoadmin   N       page
3   HomePage    2012-01-12 18:08:12     Welcome to your Wiki! [[Test]] 2 demoadmin  demoadmin   Y       page
```

And now I want to create the new page called "Test" (/index.php?module=wikula&type=user&func=main&tag=Test) and the error appears again.

---

> This appears if all revistions have the value latest = N. 

Not _all_ my revisions have this value. 

---

If I change ALL values to N, I still have the same problem.

**Comment by phaidon** [comment]
Maybe this helps. 

Otherwise: When does the error appears exactly. If you press edit or if you press save after editing the page.

**Comment by hvorragend** [comment]
Yes, the last commit helped.

The error appear directly after clicking on the question mark.

**Comment by phaidon** [comment]
Is this problem completely solved now?

**Comment by hvorragend** [comment]
Yes, it looks like.

**Comment by phaidon** [comment]
Great
